encoding: utf-8

# SEO相关信息
title: zhyjc6's Blog
description: zhyjc6的个人博客
keywords: zhyjc6,Blog
author: zhyjc6

# 这些不要动
permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
exclude: ['CNAME', 'README.md', 'build-tool']

# 域名配置
# baseUrl配置,如果网站部署在根目录下的目录中，请设置为 /目录名
domainUrl: 'https://zhyjc6.github.io'
baseUrl: ''

# 吐个槽地址，会在chat页面中重定向到该地址
tucaoUrl: https://support.qq.com/product/87134

# 菜单
menu:
  - title: 主页
    url: /
  - title: 分类
    url: /pages/categories.html
  - title: 搜索
    url: /pages/search.html
  - title: 友链
    url: /pages/links.html
  - title: 留言
    url: /pages/chat.html
  - title: 关于
    url: /pages/about.html


# 友情链接
links:
  - title: TMaize的个人博客
    url: http://blog.tmaize.net
  - title: Paper——安全技术精粹
    url: https://paper.seebug.org