encoding: utf-8

# SEO相关信息
title: zhyjc6's Blog
description: zhyjc6的个人博客
keywords: zhyjc6,Blog
author: zhyjc6
footerText: 'No Copyright'

# 这些不要动
permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
exclude: ['CNAME', 'README.md', 'build-tool']

# 域名配置
# baseUrl配置,如果网站部署在根目录下的目录中，请设置为 /目录名
domainUrl: 'https://zhyjc6.github.io'
baseUrl: ''

# 吐个槽地址，会在chat页面中重定向到该地址
tucaoUrl: https://support.qq.com/product/87134

# 菜单
menu:
  - title: Home
    url: /
  - title: Categories
    url: /pages/categories.html
  - title: Search
    url: /pages/search.html
  - title: Links
    url: /pages/links.html
  - title: Chat
    url: /pages/chat.html
  - title: About
    url: /pages/about.html

# 自定义插件,具体说明请看README文档
customPlugins:
  - use: true
    file: 'plugin-mta-stats.html'
    sid: 500697048
    cid: 500697053
  - use: true
    file: 'plugin-baidu-push.html'
  - use: true
    file: 'plugin-click-effect.html'
  - use: false
    file: 'plugin-mathjax.html'



# 友情链接
links:
  - title: TMaize的个人博客
    url: http://blog.tmaize.net
